### ISSUE TITLE
Shiny Apps Raise an error?

### ISSUE THREAD

**Issue by psychemedia** [binder-examples/dockerfile-rstudio#1]
Hi

Trying to run a shiny app from RStudio as part of an RStudio demo the path to the app appears to get lost going through the proxy path?

eg in RStudio:

```
library(shiny)
runUrl('https://gist.github.com/garrettgman/6673251/archive/78579e31f72648a88d8026c10237db1ea5d2e9af.zip')
```

launches a shiny server, and a viewer at:

`https://hub.mybinder.org/user/binder-examples-kerfile-rstudio-XXXXXXX/proxy/NNNNN/?view=shiny`

that is trying to load:

`https://hub.mybinder.org/user/binder-examples-kerfile-rstudio-XXXXXXX/proxy/NNNNN/p/MMMM`

which is not found with an error on `/p/MMMM`.

**Comment by choldgraf** [comment]
hmmm - we haven't built tooling around the extra server functionality for things like shiny...my guess is that the environment will need to be configured to allow for particular kinds of port communication etc. @yuvipanda do you have any thoughts on how we could incorporate shiny functionality into BinderHub? Maybe we do the necessary networking to allow for shiny apps if we find an `install.R` file?

**Comment by giuseppec** [comment]
@psychemedia is this still an issue or did you solve this somehow? I would be interested in how you solved it.

**Comment by psychemedia** [comment]
@giuseppec it's still on my backburner I'm afraid...

**Comment by betatim** [comment]
Closing this, as there is now a way to have RShiny in the R example repo: https://github.com/binder-examples/r
