### ISSUE TITLE
Wrong user permissions

### ISSUE THREAD

**Issue by betatim** [binder-examples/dockerfile-rstudio#3]
Everything in the container seems to be owned by root, but RStudio itself is launched as user rstudio. So you can run scripts but not save them, nor create files.

Is this a bug here or for rocker-org/binder?

**Comment by cboettig** [comment]
That's a bug here, caused by calling Docker `COPY` which is always root.  We cannot do the COPY call in the upstream `rocker/binder` image obviously since it needs to copy the user's repo.

**Comment by choldgraf** [comment]
Thanks @cboettig !!!
